import Link from 'next/link'
import React from 'react'

export default function career() {
  return (
    <>
    <div className='bg-blue-400 mt-4'>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores corrupti consequuntur explicabo sequi amet ullam repudiandae nesciunt facilis sapiente, aliquid cumque quod! Eum deleniti iste nulla dolorem explicabo, fugiat pariatur, doloremque earum accusamus dicta error perspiciatis magni ratione cupiditate illum sequi voluptate ducimus voluptatem libero ut incidunt in? Quo exercitationem commodi at provident totam. Ipsa similique architecto deserunt perspiciatis culpa. Facilis maiores asperiores eius, repellat eum accusamus necessitatibus? Deleniti, corrupti assumenda, at delectus dolorem consectetur veritatis, possimus minus culpa nihil dignissimos hic. Expedita consequatur, recusandae repellendus iste non, fugiat necessitatibus reprehenderit quidem commodi beatae nesciunt illo nulla voluptatibus minus omnis voluptatum iure! Optio dicta quas odio saepe quae tempora? Voluptatum maiores vel adipisci, tempore nulla perspiciatis voluptates fugit reprehenderit cum repellat fugiat rem porro odio doloribus, officia repellendus molestias modi laborum eveniet possimus quibusdam esse maxime eius! Suscipit, esse cumque quos quas veritatis eius incidunt sint accusantium repellendus sit reiciendis quis perferendis deleniti in alias iste fugiat ea numquam cupiditate laboriosam debitis molestiae corporis dolorem beatae. Temporibus consequatur tempore reiciendis magni soluta nisi, a praesentium molestias culpa, quas quia repellat ipsa voluptate. Inventore autem maxime doloremque unde, dolor dolorem numquam corrupti, quibusdam ratione dicta cumque, sapiente sunt sed repellendus at nisi? Praesentium neque earum aut, eius, blanditiis consequatur modi ducimus impedit repellat illum dicta officia culpa at accusantium saepe temporibus voluptas quam ut fugit mollitia ullam quis nisi sed. Natus iure tempora earum harum voluptatem atque, unde quod veniam doloribus reiciendis illum commodi aut ipsam perferendis vel repellat corporis fugit quidem? Quasi expedita assumenda nobis qui dicta magnam maxime maiores. Quidem odio delectus dolore earum nemo perspiciatis voluptates quis eos natus ad animi repellendus corporis fuga blanditiis amet, aliquam placeat consequatur fugiat ex laboriosam cum. Iure voluptatem quaerat deserunt atque quia maiores rem. Accusamus totam error repellat reprehenderit exercitationem fuga?</p>
    </div></>
  )
}
