import type { Metadata } from "next";
import Header from "@/app/components/Header"
import Footer from "@/app/components/Footer"
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import { Roboto } from "next/font/google";
import "@/app/globals.css";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400','700','900'],
  variable: '--font-roboto'
})
const poppins = Poppins({
  subsets: ['latin'],
  weight: '800',
  variable: '--font-poppins'
})

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "600",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${roboto.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
